README.md, dreamcode.md
- **docs(dreamcode): initial version**
- **docs(README): add link to dreamcode.md**
=> docs(dreamcode): initial version

dreamcode.md
Still not 100% about the difference between https://api.githubcopilot.com/chat/completions and https://models.inference.ai.azure.com/chat/completions, but I assume we will want to default the prompt base URL to https://api.githubcopilot.com/chat/completions and probably will set a default model name as well, that we prefer our users to use unless they know what they are doing
=> docs(dreamcode): prompt default to CAPI

README.md, index.d.ts, index.js, index.test-d.ts, test/integration.test.js
BREAKING CHANGE: `verify()` method has been replaced by `verifyRequestByKeyId()` for clarity
Before:
```js
import { verify } from "@copilot-extensions/preview-sdk";
const payloadIsVerified = await verify(request.body, signature, keyId, { token });
```
After
```js
import { verifyRequestByKeyId } from "@copilot-extensions/preview-sdk";
const payloadIsVerified = await verifyRequestByKeyId(request.body, signature, key, { token });
```
=> feat: `verifyRequestByKeyId()`, `verifyRequest()`, `fetchVerificationKeys()`

README.md, dreamcode.md
=> docs(dreamcode): mention interop functionality and show code how requset parsing and the event API will work

index.d.ts, index.test-d.ts, lib/prompt.js, test/prompt.test.js
=> feat: `options.tools ` for `prompt()`

README.md, index.d.ts, index.test-d.ts, lib/prompt.js, test/prompt.test.js
=> feat: `options.messages` for `prompt()`

dreamcode.md
=> docs(dreamcode): function calling example

README.md, index.d.ts, index.test-d.ts, lib/prompt.js, test/prompt.test.js
- **fix(types): `ModelName` is a string now**
- **docs(README): `model` parameter is no longer required for `prompt()`. It defaults to `gpt-4`**
- **fix: `model` parameter is now optional for `prompt()`. It defaults to `gpt-4`**
=> fix(prompt): `parameters.model` is now a string and is optional. It defaults to `gpt-4`

README.md, index.d.ts, index.test-d.ts, lib/prompt.js, test/prompt.test.js
BREAKING CHANGE: `prompt()` is now throwing an error if the API responds with an error status code
=> feat(prompt): `prompt.stream()`, `options.endpoint`

README.md, index.d.ts, index.test-d.ts, lib/response.js, test/response.test.js, test/response.test.js.snapshot
closes #58
BREAKING CHANGE: All `create*Event` methods now return a string instead of an object with a `.toString()` method.
Before:
```js
esponse.write(createTextEvent("Hello, world!").toString());
```
Now:
```js
esponse.write(createTextEvent("Hello, world!"));
```
=> feat: `create*Event` methods now return strings

index.d.ts, index.test-d.ts, lib/prompt.js, test/prompt.test.js
this aligns with other uses across github
=> fix: use `gpt-4o` as default model

README.md
This updates the README's reference to the CONTRIBUTING.md file to the correct location at root, rather than its previous location in `.github/CONTRIBUTING.md`.
=> docs(`README.md`): point to `CONTRIBUTING.md` at root of directory

.devcontainer/devcontainer.json
Closes https://github.com/copilot-extensions/preview-sdk.js/issues/68
This change standardizes the configuration for development on GitHub Codespaces.
Specifically:
- It uses the [`mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm` image](https://github.com/devcontainers/images/blob/main/src/typescript-node/README.md) specifying Node version `22`, [a prerequisite of running this project](https://github.com/copilot-extensions/preview-sdk.js/blob/main/CONTRIBUTING.md#prerequisites)
- Runs `npm install` after the container is created.
Happy to edit this as-is helpful for the team's development flow 👍
=> Add dev container configuration for developing with Codespaces

CONTRIBUTING.md
Previously, the Contributing guide specified `github-project` as a reference to this project's name.
This PR updates the name to it's repository name with owner, `copilot-extensions/preview-sdk.js`.
=> docs(CONTRIBUTING.md): use the name of this project

.github/workflows/test.yml
thanks to #78, we can now test in Node 20
=> ci(test): test in Node 20

examples/hello-world-without-sdk/index.js, examples/hello-world-without-sdk/package.json
=> docs(examples): hello-world-without-sdk

test/parse.test.js
Improve test coverage for `parse.js` file. Concretely for `getUserConfirmation()` method.
relates to https://github.com/copilot-extensions/preview-sdk.js/issues/87
=> test(parse): add test coverage when no copilot_confirmations present

lib/prompt.js, test/prompt.test.js
- **test(prompt): add 100% test coverage for `parsePromptArguments()`**
- **test(prompt): add test coverage for prompt.stream()**
Relates to #87
=> test(prompt): improve test coverage for prompt.js

README.md
Adding links to general extension docs to the README.
Give builders a pathway to Extension Builders docs if they want to learn more.
Links to docs in the footer.
Any specific docs pages we should/shouldn't be linking
=> docs(README): add links to official Copilot Extensions documentation

lib/response.js
A refactoring opportunity: after reading `createAckEvent()` and `createTextEvent`'s definitions, I noticed that the only difference was that the former passes in an empty string for its content.
I chose to update the body to use `createTextEvent()` directly, passing an empty string for its `message` argument. Ran tests locally and in CI to verify this works 👍 
Nothing I haven't mentioned 😉
=> refactor: reuse `createTextEvent()` in `createAckEvent()`

README.md
Adds a small change to the `README.md` file. The change updates the example code to use `await` with the `prompt.stream` method for proper asynchronous handling.
=> fix(readme): add `await` to `prompt.stream` example
